### ISSUE TITLE
small issues with game 

### ISSUE THREAD

**Issue by WilliamLampke** [MarchandMD/battleship#22]
printing message to start game after its over (fix by removing the welcome_message(s) from the game_over method)
~~the shot hit/miss message prints too far above in the console to actually read so we need to rearrange that if possible but not a huge deal~~

**Comment by MarchandMD** [comment]
I agree that the shot/hit/miss message prints too far above....I'll take that issue. 

As far as what happens when the game is over....that sort of is part of iteration 3.... so maybe instead of removing `#welcome_message` from `#game_over`.... maybe the project needs some way to start the game again after the game is over? 

I don't know how that would work though.....

**Comment by MarchandMD** [comment]
Fixed the issue with the messages printing too far apart; submitting PR RN

**Comment by MarchandMD** [comment]
this is completed

**Comment by WilliamLampke** [comment]
maybe a slight change to the loop

**Comment by MarchandMD** [comment]
this issue has been fixed and will be gone once the next PR is merged
